AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  simple-websockets-chat-app

  SAM Template for simple-websockets-chat-app that has the DynamoDB table and Lambda
  functions needed to demonstrate the Websocket protocol on API Gateway.

Parameters:
  DemoName:
    Type: String
    Default: gpt-bot
    MinLength: 3
    MaxLength: 50
  SecretName:
    Type: String
    Description: Name of the secret in AWS Secrets Manager
Resources:
  #API GATEWAY
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn
        AddDefaultAuthorizerToCorsPreflight: false
      DefinitionBody:
        swagger: "2.0"
        schemes:
          - https
        paths:
          /main:
            post:
              summary: Send Message
              responses: {}
              x-amazon-apigateway-integration:
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${callOpenAI.Arn}/invocations
                httpMethod: POST
                passthroughBehavior: when_no_templates

  callOpenAI:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: nodejs16.x
      Timeout: 100
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /send
            Method: POST
            RestApiId:
              Ref: ApiGatewayApi
      Handler: index.handler
      CodeUri: handler/main
      Environment:
        Variables:
          SECRET_NAME: !Ref SecretName
      Policies:
        Statement:
          - Effect: Allow
            Action: secretsmanager:GetSecretValue
            Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretName}

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
